site_name: 《以撒的积木》文档
extra_javascript:
  - api.js?v=1
plugins: []
theme:
  name: readthedocs
  locale: zh
nav:
  - 主页: 'index.md'
  - 文字教程:
    - 一 基本操作: 'text_tutorial/1.basic_operate.md'
    - 二 积木搭建规则: 'text_tutorial/2.block_basic_rule.md'
    - 三 类型系统: 'text_tutorial/3.type_system.md'
    - 四 逻辑积木: 'text_tutorial/4.block_logic.md'