site_name: 《以撒的积木》文档
extra_javascript:
  - api.js
plugins: []
theme:
  name: readthedocs
  locale: zh
nav:
  - 主页: 'index.md'
  - 文字教程:
    - 基本操作: 'text_tutorial/1.basic_operate.md'
    - 积木搭建规则: 'text_tutorial/2.block_basic_rule.md'